# Generated by Django 3.1.3 on 2020-12-08 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20201208_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinbasket',
            name='price',
        ),
    ]
