# Generated by Django 3.1.3 on 2020-11-16 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default=None, upload_to='products_image/'),
            preserve_default=False,
        ),
    ]
