# Generated by Django 3.1.3 on 2020-11-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20201124_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='new_name',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
