# Generated by Django 3.1.3 on 2020-12-03 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_new_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='new_name',
        ),
    ]
